var gods = [
  {
    "name": "Achilles",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "execute",
    "subfunction2": ""
  },
  {
    "name": "Anhur",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "crit",
    "subfunction2": ""
  },
  {
    "name": "Anubis",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Ao Kuang",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "execute",
    "subfunction2": ""
  },
  {
    "name": "Aphrodite",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "heal",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Apollo",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Arachne",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Ares",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "Artemis",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "annoy",
    "preffunction2": "kill",
    "subfunction1": "cc",
    "subfunction2": "crit"
  },
  {
    "name": "Athena",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": ""
  },
  {
    "name": "Bacchus",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": ""
  },
  {
    "name": "Bastet",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Bellona",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Cerberus",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "kill",
    "subfunction1": "cc",
    "subfunction2": "truedmg"
  },
  {
    "name": "Chang'e",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "heal",
    "preffunction2": "kill",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Chiron",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Chronos",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "stun",
    "subfunction2": ""
  },
  {
    "name": "Cupid",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "Hunter",
    "preffunction1": "mobility",
    "preffunction2": "heal",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Da Ji",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Discordia",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": ""
  },
  {
    "name": "Erlang Shen",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Fafnir",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Fenrir",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Freya",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Geb",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "protect",
    "preffunction2": "annoy",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "Guan Yu",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "heal",
    "preffunction2": "mobility",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Hades",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "He Bo",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "kill",
    "subfunction1": "just annoy",
    "subfunction2": "truedmg"
  },
  {
    "name": "Hel",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "heal",
    "preffunction2": "protect",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Hera",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "Hercules",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "Horus",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "protect",
    "preffunction2": "mobility",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Hou Yi",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "crit",
    "subfunction2": ""
  },
  {
    "name": "Isis",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "protect",
    "preffunction2": "kill",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Janus",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Jing Wei",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "crit",
    "subfunction2": ""
  },
  {
    "name": "Jormungandr",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Khepri",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "protect",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Loki",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": ""
  },
  {
    "name": "Medusa",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "crit",
    "subfunction2": ""
  },
  {
    "name": "Mercury",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "mobility",
    "preffunction2": "kill",
    "subfunction1": "crit",
    "subfunction2": ""
  },
  {
    "name": "Ne Zha",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "crit",
    "subfunction2": ""
  },
  {
    "name": "Neith",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "crit",
    "subfunction2": ""
  },
  {
    "name": "Nemesis",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Nike",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "protect",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Nox",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "mobility",
    "preffunction2": "annoy",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "Nu Wa",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "stun",
    "subfunction2": ""
  },
  {
    "name": "Odin",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Osiris",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Persephone",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Poseidon",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "Ra",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "heal",
    "subfunction1": "just annoy",
    "subfunction2": ""
  },
  {
    "name": "Ratatoskr",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Scylla",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Serqet",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Set",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": ""
  },
  {
    "name": "Skadi",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "crit",
    "subfunction2": ""
  },
  {
    "name": "Sobek",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "Sol",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Sun Wukong",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "annoy",
    "preffunction2": "mobility",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "Sylvanus",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "heal",
    "preffunction2": "annoy",
    "subfunction1": "cc",
    "subfunction2": ""
  },
  {
    "name": "Terra",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "heal",
    "preffunction2": "protect",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Thanatos",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": ""
  },
  {
    "name": "Thor",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Thoth",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Tyr",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Ullr",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Vulcan",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": ""
  },
  {
    "name": "Xing Tian",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "kill",
    "subfunction1": "cc",
    "subfunction2": "truedmg"
  },
  {
    "name": "Ymir",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "stun",
    "subfunction2": "cc"
  },
  {
    "name": "Zeus",
    "pantheon": "Greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": ""
  },
  {
    "name": "Zhong Kui",
    "pantheon": "Chinese",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": ""
  }
]