[
  {
    "name": "Achilles",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "execute",
    "subfunction2": "",
    "note": "Execute enemies on your ultimate."
  },
  {
    "name": "Anhur",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "crit",
    "subfunction2": "",
    "note": "Anhur is one swift and killing lion. Build for critical chance combined with ulti = killing spree, and fast!"
  },
  {
    "name": "Anubis",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Ao Kuang",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "execute",
    "subfunction2": "",
    "note": "Stealth, bonus damage from abilities and during your ultimate you can execute your enemies and then turn into giant dragon. Do your best!"
  },
  {
    "name": "Aphrodite",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "heal",
    "preffunction2": "protect",
    "subfunction1": "",
    "subfunction2": "",
    "note": "Not only she can heal others with her birds (3), she can also push enemies back with her 2 and provide invincibility with her ultimate. Oh, and as a bonus, her 1 can also stun enemy and provide buff for your ally. <BR> Get used to these birds chirping!"
  },
  {
    "name": "Apollo",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": "God of many things but in smite mostly of music and running faster than most. He's not only fast, he also posseses dash, as well as ultimate which allows him to drop anywhere on map. Easy in, out and out-and-in way to teamfights."
  },
  {
    "name": "Arachne",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "Late game and her basic attacks simply melt down enemies."
  },
  {
    "name": "Ares",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": "Try your ultimate with high cooldown reduction. And with Blink. And if someone survives, use chains to slow them down. If your team follows you, enemies may surrender sooner than you expect."
  },
  {
    "name": "Artemis",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "annoy",
    "preffunction2": "kill",
    "subfunction1": "cc",
    "subfunction2": "crit",
    "note": "She can place roots and her ulti stuns all enemies one by one, so no teamwork is easy for them."
  },
  {
    "name": "Athena",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": "",
    "note": "Annoying, ah, yes, she is! To enemies mostly because her long taunts. And ultimate which allows her drop onto an ally and cause damage around her. To allies too, when she spams charching her dash non-stop. It makes a sound, you know, and after a while you'll pray for enemies ganking to keep her occupied."
  },
  {
    "name": "Bacchus",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": "",
    "note": "He gets drunk. He's a god of wine after all. The more drunk he gets, the more powerful his burps are and the more ovewhelming his smashed jug... I mean, his ultimate is. <br> He can be disgustingly annoying not only thanks to how he sounds but also to amount of crowd control he posses."
  },
  {
    "name": "Bastet",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "Invest in cooldown reduction. Your ultimate is as annoying as it can be deadly."
  },
  {
    "name": "Bellona",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Cerberus",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "kill",
    "subfunction1": "cc",
    "subfunction2": "truedmg",
    "note": "He can kill, he can annoy enemies by throwing them into teamfights when they try to escape or slow them down significantly, he can also heal himself and allies. He also has 3 heads. Good doggo."
  },
  {
    "name": "Chang'e",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "heal",
    "preffunction2": "kill",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "She can heal and she can kill and she can also avoid a lot of damage just like that. If you look for easy and viable healer, look no further."
  },
  {
    "name": "Chiron",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "",
    "subfunction2": "",
    "note": "Half-man, half-horse. He can crit beautifully, but he's also really mobile in and out of fights. And if you find yourself stuck, remember that his 1 not only damages enemies, but also cleanses you from any crowd control. Use this before your 3 and you're safely out!"
  },
  {
    "name": "Chronos",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "stun",
    "subfunction2": "",
    "note": "This man can do a lot of damage but most annoying part of facing Chronos? His stuns every couple of seconds. Just no. No."
  },
  {
    "name": "Cupid",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "Hunter",
    "preffunction1": "annoy",
    "preffunction2": "heal",
    "subfunction1": "stun",
    "subfunction2": "",
    "note": "Hunter, yes, in right hands he kills with a snap of his fingers. But on top of that he can heal himself and others and annoy enemies with his stuns (yes, more than one). <br> Also, if you have a voicepack, VGS waits to be used. Spam commands only if you want to annoy your teammates as well."
  },
  {
    "name": "Da Ji",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "Leap to enemy/ally, buff to movement speed and her ultimate that can save her life and cost a life of an enemy. What's not to like?"
  },
  {
    "name": "Discordia",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": "",
    "note": "Ah, the goddes of discord. Pay attention and use your 2 and ultimate wisely (which sometimes mean \"all the time\"). There's nothing more annoying than first being forced to fight your ally, then getting hit by giant golden apple, then spread the apple to others (and probably being flamed for that) and die from getting hit by her 1 ricocheting. <br> Good time for Discordia, bad time for the enemies."
  },
  {
    "name": "Erlang Shen",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Fafnir",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Fenrir",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": "If you want to make your enemy just as mobile as you, grab them with your jaws and carry towards your allies. I'm sure they'll appreciate it."
  },
  {
    "name": "Freya",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Geb",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "protect",
    "preffunction2": "annoy",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Guan Yu",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "heal",
    "preffunction2": "mobility",
    "subfunction1": "",
    "subfunction2": "",
    "note": "Dash + horseriding while being cc immune. And you can heal yourself and others. If you know what you're doing that also means not dying for a long time."
  },
  {
    "name": "Hades",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "He Bo",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "kill",
    "subfunction1": "just annoy",
    "subfunction2": "truedmg",
    "note": ""
  },
  {
    "name": "Hel",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "heal",
    "preffunction2": "protect",
    "subfunction1": "",
    "subfunction2": "",
    "note": "It's like two gods for the price of one. She can do damage but she also heals and clenses allies and after she switches stances she shares the benefits of that with others. Keeping others alive has never been that easy."
  },
  {
    "name": "Hera",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": "Hera turns her enemies into animals and drops a giant mech on them. That's in short."
  },
  {
    "name": "Hercules",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Horus",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "heal",
    "preffunction2": "mobility",
    "subfunction1": "",
    "subfunction2": "",
    "note": "Recent addition to god pool: majestic birbo. He protecc, he attacc but most importantly he does not give... <br> No, really, he has defenses up so high that he can withstand a lot of damage and not blink an eye. Not so squishy as some other warriors, he has two dashes (one of them heals allies in the area) and ultimate that allows him to fly quite significant distance - and also to carry some other teammates with him."
  },
  {
    "name": "Hou Yi",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "crit",
    "subfunction2": "",
    "note": "He flies for longer than some birds in the game. I guess that counts a lot for mobility. <br> Don't forget you can stun marked enemies with your 1 and that your ultimate not ony deals damage but slows them down A LOT too."
  },
  {
    "name": "Isis",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "protect",
    "preffunction2": "kill",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "She's intended to be protective support... I guess? But what she does amazing is also killing enemies. Use your 1 to be fast and deadly, use your 2 to be stunning and deadly, use your ultimate to be... well, deadly (and helpful to your allies too!)"
  },
  {
    "name": "Janus",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": "Make yourself faster and slow your enemies. Your portals can, well, teleport you through obstacles and walls. The art of disappearing is your art and going from A to B has never been easier."
  },
  {
    "name": "Jing Wei",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "crit",
    "subfunction2": "",
    "note": "Her passive offers flying out of the fountain. Then she has dash and ultimate which is also dash but more like an airstrike."
  },
  {
    "name": "Jormungandr",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": "He's a big guy and he can cross half of the map with his ulti. He can be invisible and fast too. Somehow being giant dragon doesn't make invisibility part harder for him."
  },
  {
    "name": "Khepri",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "protect",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": "Khepri can resurrect fallen teammate or even himself. It really is <i>ultimate</i> protection."
  },
  {
    "name": "Loki",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": "",
    "note": "What are you doing here? You knew Loki is the answer way before you pressed that button."
  },
  {
    "name": "Medusa",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": "Strafing left and right faster than for other gods may not look impressive. Try it out dodging enemy's basic attacks and then shooting them yourself."
  },
  {
    "name": "Mercury",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "mobility",
    "preffunction2": "kill",
    "subfunction1": "crit",
    "subfunction2": "",
    "note": "Fastest movement speed in game and ultimate dash through entire map."
  },
  {
    "name": "Ne Zha",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "crit",
    "subfunction2": "",
    "note": "Guaranteed critical hits for abilities and damage that spreads to other enemies. It's like very good multitasking, where the task is to kill someone."
  },
  {
    "name": "Neith",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "crit",
    "subfunction2": "",
    "note": "Neith may be easy to pick up and easy to master but it's always pleasure to hit someone from across the map and get a kill. Or to root three people in place and send the arrows on them. Or to just jump out of range last minute when someone tries to stun you and laugh in their face."
  },
  {
    "name": "Nemesis",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "Dash, kill, dash again. Rinse, repeat."
  },
  {
    "name": "Nike",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "protect",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Nox",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "mobility",
    "preffunction2": "annoy",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": "Silence, root, and dash, all in one goddess. She is annoying, she is fast and she can be very deadly."
  },
  {
    "name": "Nu Wa",
    "pantheon": "chinese",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "stun",
    "subfunction2": "",
    "note": "Invest in cooldown reduction and mana. Then spend it all on spawning your minions and detonating them to stun enemies. Easy! Bonus points for using your ultimate when your enemies are running away on low health. Now THIS is really annoying."
  },
  {
    "name": "Odin",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": "Now this was hard to assign. Is Odin a killing machine? Is he mobile enough? Or is he just annoying with his huge cage that suddenly locks teamfights in a very small space? Yeah, he is that for sure. And someone will have to waste relic place to just get everyone free while they are screaming \"lettt meeeee ouuuutttt\"."
  },
  {
    "name": "Osiris",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Persephone",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Poseidon",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": "Your 1 pushes enemies, your 3 drags them and slows them and your ultimate is a GIANT KRAKEN throwing everyone into the air. You know, you want to play him."
  },
  {
    "name": "Ra",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "heal",
    "subfunction1": "just annoy",
    "subfunction2": "",
    "note": "1. Spamming [VEL] Laugh will definitely annoy your teammates early in the game <br> 2. with Chibi Ra skin just play the game and your abilities will make everyone on both teams scream internally <br> 3. With 40% reduction cooldowns and a bit of sniper reflex you will make opposing teams game a nightmare"
  },
  {
    "name": "Ratatoskr",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "kill",
    "preffunction2": "mobility",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "As a god-like squirrel you don't wear shoes but still have better movement speed than half of the gods in game. It's one of these assassins when people start spamming \"Behind us!\" when they see you jumping across the sky."
  },
  {
    "name": "Scylla",
    "pantheon": "greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "<a href=\"https://www.youtube.com/watch?v=6CqBlyA0vaY\" target=\"_blank\">\"I'm a monster!\"</a>"
  },
  {
    "name": "Serqet",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": "Three abilities have movement included."
  },
  {
    "name": "Set",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": "",
    "note": "Annoy... I don't know who more - yourself or enemies? Either them with your little cute sand clones if you know how to handle them and you appearing out of nowhere and wayyy too close, or yourself if the team is not really reliable and more teamfights end up with ulti wasted rather than used."
  },
  {
    "name": "Skadi",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "crit",
    "subfunction2": "",
    "note": "She lets the dog out. <br> Also one word: Permafrost. Make them slide, make them slide a lot."
  },
  {
    "name": "Sobek",
    "pantheon": "egyptian",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": "Dash, stun, throw behind the back, spin around to throw them in the air. Rinse, repeat."
  },
  {
    "name": "Sol",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "Both basic attacks and abilities are equally useful and she can survive and fight both short (1, 2, 4) and long range (2, 4). <br> Bonus points if you kill someone accidentally while running away with your 3."
  },
  {
    "name": "Sun Wukong",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "annoy",
    "preffunction2": "mobility",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": "It may take a game or two to figure out how to play him."
  },
  {
    "name": "Sylvanus",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "heal",
    "preffunction2": "annoy",
    "subfunction1": "cc",
    "subfunction2": "",
    "note": "Remember: the actual god is this little guy on the tree, not tree itself!"
  },
  {
    "name": "Terra",
    "pantheon": "roman",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "heal",
    "preffunction2": "protect",
    "subfunction1": "",
    "subfunction2": "",
    "note": "Duel two Terras is painfully boring, as they can heal for the amout of damage they receive. More or less."
  },
  {
    "name": "Thanatos",
    "pantheon": "greek",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": "",
    "note": "There's so many thing annoying about this god... If you played Smite before, you know exactly what I'm talking about."
  },
  {
    "name": "Thor",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "assassin",
    "preffunction1": "mobility",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": "You can dash using your 1, your ultimate let you drop on the map and do it quite fast. It's deadly too, especially after latest buff."
  },
  {
    "name": "Thoth",
    "pantheon": "egyptian",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "Skinny birb using ancient Egyptian magic. Your 3 makes all ranged attacks hitting harder. Use it against objectives and enemies, with your basics and basically everything you have. <br> Ouch."
  },
  {
    "name": "Tyr",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "physical",
    "smiteclass": "warrior",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Ullr",
    "pantheon": "norse",
    "attacktype": "ranged",
    "powertype": "physical",
    "smiteclass": "hunter",
    "preffunction1": "",
    "preffunction2": "",
    "subfunction1": "",
    "subfunction2": "",
    "note": ""
  },
  {
    "name": "Vulcan",
    "pantheon": "roman",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "just annoy",
    "subfunction2": "",
    "note": "You will be frustrating on maps limited with walls. Your cannon will block the way, bomb will knock back enemies and ultimate is... Well, it is bigger than everything else in the game."
  },
  {
    "name": "Xing Tian",
    "pantheon": "chinese",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "kill",
    "subfunction1": "cc",
    "subfunction2": "truedmg",
    "note": "Root your enemies or throw them using your axe. Or both, you can do both."
  },
  {
    "name": "Ymir",
    "pantheon": "norse",
    "attacktype": "melee",
    "powertype": "magical",
    "smiteclass": "guardian",
    "preffunction1": "annoy",
    "preffunction2": "",
    "subfunction1": "stun",
    "subfunction2": "cc",
    "note": "Btw. Put that announcer pack up. <a href=\"https://www.youtube.com/watch?v=vl-aEzQOBBU\" target=\"_blank\">\"Cooler than Ymir's toes\"</a>"
  },
  {
    "name": "Zeus",
    "pantheon": "Greek",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": "Just charge these charges and don't forget to detonate them. EASY."
  },
  {
    "name": "Zhong Kui",
    "pantheon": "Chinese",
    "attacktype": "ranged",
    "powertype": "magical",
    "smiteclass": "mage",
    "preffunction1": "kill",
    "preffunction2": "",
    "subfunction1": "truedmg",
    "subfunction2": "",
    "note": ""
  }
];